### ISSUE TITLE
Install instructions need to be updated for multisite implementation of the module

### ISSUE THREAD

**Issue by Souvik-Inno** [innoraft/drupal-quality-checker#18]
Found the following issues while implementing the module for multisite:

1. For ESLint task Setup:
    This command gives error as .eslintrc.json cannot find airbnb which is present in the custom theme package.json
    Now run this command at project's root directory
    `cp vendor/innoraft/drupal-quality-checker/eslintrc.json.dist .eslintrc.json`
2. Same issue for Stylelint task Setup like ESLint task Setup along with need to run another command 
    `npm install stylelint-config-standard`

**Comment by Souvik-Inno** [comment]
#19 Contains the solution of this issue, @kunal-sin please check this PR.

**Comment by kunal-sin** [comment]
Thanks @Souvik-Inno for the help.
PR is merged!
